---
# tasks file for spacewalk-client--role
- name: (All) Ensure environment file exists
  file:
    path: "{{ environment_file }}"
    owner: "{{ environment_file_owner }}"
    group: "{{ environment_file_group }}"
    state: touch
  register: environment_file_result
  changed_when: environment_file_result.diff.before.state != "file"

- name: (All) Configuring environment
  lineinfile:
    dest: "{{ environment_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^LANGUAGE=', line: 'LANGUAGE="en_US:en"' }
    - { regexp: '^LC_ALL=', line: 'LC_ALL="en_US.utf8"' }
    - { regexp: '^LC_CTYPE=', line: 'LC_CTYPE="en_US.utf8"' }
    - { regexp: '^LANG=', line: 'LANG="en_US.utf8"' }
    - { regexp: '^no_proxy=', line: 'no_proxy="127.0.0.1, localhost, {{ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0])}}, {{ spacewalk_hostname }}"' }

- name: (All) Ensure spacewalk hostname in /etc/hosts
  lineinfile: dest=/etc/hosts regexp=^{{ spacewalk_ip }} line="{{ spacewalk_ip }} {{ spacewalk_hostname }}"

- name: (CentOS) install spacewalk repository
  yum: name=https://copr-be.cloud.fedoraproject.org/results/%40spacewalkproject/spacewalk-2.9-client/epel-{{ansible_distribution_major_version}}-x86_64/00911911-spacewalk-repo/spacewalk-client-repo-2.9-4.el{{ansible_distribution_major_version}}.noarch.rpm  state=present
  when: ansible_distribution == "CentOS"

 
- name: (CentOS 7) install extra packages
  yum: name=epel-release state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: (CentOS) Install required client packages
  yum:
    name: ['rhn-client-tools', 'rhn-check', 'rhn-setup', 'rhnsd', 'm2crypto', 'yum-rhn-plugin', 'osad']
    state: present
  when: ansible_distribution == "CentOS"

- name: (CentOS) Create archive directory for existing yum repos
  file:
    path: /etc/yum.repos.d/archive
    state: directory
  when: ansible_distribution == "CentOS"

- name: (CentOS) Remove existing yum repos
  shell: mv /etc/yum.repos.d/* /etc/yum.repos.d/archive
  ignore_errors: yes
  when: ansible_distribution == "CentOS"
  
- name: (Systemd) Start OSAD client
  systemd:
    name: osad
    state: started
    enabled: yes
    masked: no
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7" or ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == "18"
  
- name: (Init) Start OSAD client
  service:
    name: osad
    state: started
    enabled: yes
    masked: no
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6" or ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == "16"
  
- name: (All) Enable rhn_check client via cron (required for check-in)
  cron:
    name: rhn_check
    weekday: "*"
    minute: "0"
    hour: "*/4"
    user: root
    job: "bash -c 'sleep $(( ( RANDOM % 240 ) ))m' ; /usr/sbin/rhn_check"
    cron_file: ansible_rhn_check