---
# tasks file for spacewalk-server-role

- name: Hostname change
  hostname:
    name: spacewalk.azatcloudsolution.net

- name: Install prerequisites
  package:
    name:  
    - wget
    - unzip
    - epel-release      
    state: latest  

- name: Update hosts file on server
  lineinfile:
    path: /etc/hosts
    line: "3.236.17.66 spacewalk.azatcloudsolution.net"
     
- name: Install Firewalld
  yum:
    name: firewalld

- name: Start Firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Firewall setup
  command: firewall-cmd --permanent --add-service=http
  command: firewall-cmd --permanent --add-service=https
  command: firewall-cmd --permanent --add-port=5222/tcp --add-port=5269/tcp --add-port=69/udp

- name: Reload firewall
  command: firewall-cmd --reload

- name: Oracle staff
  command: yum install -y oracle-epel-release-el7
  command: yum install -y yum-utils
  command: yum-config-manager --enable ol7_optional_latest
  command: yum-config-manager --enable ol7_developer_EPEL
  command: yum-config-manager --enable ol7_addons
  

- name: Install plugin tmprepo
  command: yum install -y yum-plugin-tmprepo

- name: Install Spacewalk 2.10 repo
  command: yum install -y spacewalk-repo --tmprepo=https://copr-be.cloud.fedoraproject.org/results/%40spacewalkproject/spacewalk-2.10/epel-7-x86_64/repodata/repomd.xml --nogpg

 
- name: Spacewalk setup psql
  command: yum -y install spacewalk-setup-postgresql

- name: Install spacewalk psql
  command: yum install -y spacewalk-postgresql


- name: Cleanup any existing psql
  command: rm -Rf /var/lib/pgsql/data

- name: Init psql
  command: postgresql-setup initdb

- name: Copy file answers.txt
  copy:
    src: answers.txt
    dest: /tmp/

- name: Spacewalk-setup
  command: spacewalk-setup --answer-file=/tmp/answers.txt  --non-interactive


   
# *************************End*******


